### ISSUE TITLE
rasmifize changes characters 

### ISSUE THREAD

**Issue by r-shahpasand** [suchmaske/rasmifize#1]
Hi. First of all, I would like to thank you for your valuable work. 
rasmifize renders the word with **ئ** incorrectly. For example
**وَتُبۡرِئُ**  
is rendered to
**وٮٮرٮ**
which is totally a different word. The correct form is **وٮٮرى**.

**Comment by suchmaske** [comment]
Hi, @RShpd 

that's odd. I just ran the unit tests with the comparisons and also check the [demo webpage](https://suchmaske.github.io/rasmifize/demo/). Both look good on my end. What context are you using rasmifize in?

![grafik](https://user-images.githubusercontent.com/4989253/104307924-2411a900-54d0-11eb-9680-f8b550b06a59.png)

**Comment by r-shahpasand** [comment]
Thanks for your reply. I tested it again:

![image](https://user-images.githubusercontent.com/39431294/104491861-10596600-55e8-11eb-9fd9-e46da9414fef.png)
Maybe the combination of words in the sentence has caused this.  I'm using Windows 10 and Chrome.
I will add the phrase so you can test it too.
 بِإِذۡنِیۖ  وَتُبۡرِئُ  ٱلۡأَكۡمَهَ

**Comment by suchmaske** [comment]
@RShpd Hi again,

could you also provide how the sentence is supposed to look correctly?

**Comment by suchmaske** [comment]
@RShpd I think I figured out the problem and fixed it.

I only replaced yeh with alef maksura at the end of the string, not of the word. Please check the [demo page](https://suchmaske.github.io/rasmifize/demo/) again and tell me whether it is working for you. :)

**Comment by r-shahpasand** [comment]
Hi. Yes it works like a charm. Thank you.
